services:
    victoire_core.widget_image_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\BaseWidgetContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Image }
    #alias to the entity
    victoire.widget.image:
        class: Victoire\Widget\ImageBundle\Entity\WidgetImage

    #alias to the form
    victoire.widget.form.image:
        class: Victoire\Widget\ImageBundle\Form\WidgetImageType
        tags:
            - { name: form.type , alias: victoire_widget_form_image}

